[package]
name = "defguard-wireguard"
version = "0.1.0"
edition = "2021"

[features]
boringtun = ["dep:boringtun"]

[dependencies]
base64 = "0.13"
boringtun = { version = "0.4", optional = true }
log = "0.4"

[target.'cfg(target_os = "freebsd")'.dependencies]
nix = { version = "0.26", features = ["ioctl", "socket"] }

[target.'cfg(target_os = "linux")'.dependencies]
netlink-packet-core = "0.7"
netlink-packet-generic = "0.3"
netlink-packet-route = "0.17"
netlink-packet-wireguard = "0.2"
netlink-sys = "0.8"

[profile.release]
lto = "thin"
strip = "symbols"
